CREATE TABLE [dbo].[da_cut] (
  [id] int  IDENTITY(1,1) NOT NULL,
  [cutid] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [Operator] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [Levels] int  NULL,
  [FileName] nvarchar(250) COLLATE Chinese_PRC_CI_AS  NULL,
  [FilePath] nvarchar(250) COLLATE Chinese_PRC_CI_AS  NULL,
  [LoadTime] datetime  NULL,
  [ModiTime] datetime  NULL,
  [ModiContent] nvarchar(250) COLLATE Chinese_PRC_CI_AS  NULL,
  [Fabric_Name] nvarchar(250) COLLATE Chinese_PRC_CI_AS  NULL,
  [MarkLength] real  NULL,
  [SpreadLength] real  NULL,
  [ScaleLength] real  NULL,
  [MarkWidth] real  NULL,
  [SpreadWidth] real  NULL,
  [ScaleWidth] real  NULL,
  [MarkLayers] real  NULL,
  [SpreadLayers] real  NULL,
  [sets] int  NULL,
  [MarkPieces] int  NULL,
  [CutPieces] int  NULL,
  [MarkPerimeter] float(53)  NULL,
  [CutPerimeter] float(53)  NULL,
  [StartTime] datetime  NULL,
  [EndTime] datetime  NULL,
  [TotalTime] real  NULL,
  [BetweenTime] real  NULL,
  [StartData] datetime  NULL,
  [EndData] datetime  NULL,
  [TotalData] real  NULL,
  [PosTime] real  NULL,
  [CutSpeed] real  NULL,
  [MoveSpeed] real  NULL,
  [EffectiveTime] real  NULL,
  [SharpenDistance] real  NULL,
  [Sharpen] int  NULL,
  [CutSharpen] real  NULL,
  [OutsideSharpen] real  NULL,
  [TotalSharpen] real  NULL,
  [disruptTime] real  NULL,
  [disrupt] int  NULL,
  [FaultTime] real  NULL,
  [Fault] int  NULL,
  [MoveTime] real  NULL,
  [ChangeLineTime] real  NULL,
  [IdleTime] real  NULL,
  [Drill] int  NULL,
  [DrillTime] real  NULL,
  [Punch] int  NULL,
  [PunchTime] real  NULL,
  [Plan_] int  NULL,
  [PlanID] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
  [Overcut] int  NULL,
  [Overcuts] int  NULL,
  [Personnel] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
  CONSTRAINT [PK_da_cut] PRIMARY KEY CLUSTERED ([id])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)  
ON [PRIMARY]
)  
ON [PRIMARY]
GO

ALTER TABLE [dbo].[da_cut] SET (LOCK_ESCALATION = TABLE)